
disabled_rules: # rule identifiers to exclude from running
 - line_length
 - control_statement
 - force_cast
 - orphaned_doc_comment
 - large_tuple
 - cyclomatic_complexity
 - function_parameter_count
 - redundant_string_enum_value
 - multiple_closures_with_trailing_closure
 - trailing_whitespace
 - todo
# - identifier_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - Source/ExcludedFolder # Exclude specific folder from linting
 - Source/ExcludedFile.swift # Exclude specific file from linting
 
# parameterized rules can be customized from this configuration file
# parameterized rules are first parameterized as a warning level, then error level.
file_length:
 - 900 # warning
 - 1500 # error
function_body_length:
 - 200 # warning
 - 300 # error
type_body_length:
 - 300 # warning
 - 400 # error
vertical_whitespace: # warning, max_empty_lines: 1
 max_empty_lines: 3 # warning

# If you would like to generate report and export it
# reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)


 
