# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'OchsnerInhalerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OchsnerInhalerApp
  pod 'AlamofireObjectMapper', '~> 5.2.0'
	pod 'KeychainSwift', '~> 19.0.0'
 	pod 'MBProgressHUD', '~> 1.2.0'
	pod 'CocoaLumberjack/Swift', '~> 3.7.0'
  pod 'DropDown'
  pod 'SwiftLint'
  pod 'Firebase/Analytics', '~> 8.4.0'
  pod 'Firebase/Crashlytics', '~> 8.4.0'
end
